CREATE DATABASE Pracownicy;
USE Pracownicy;
CREATE TABLE Pracownicy (
ID INTEGER UNIQUE PRIMARY KEY,
Imię TEXT NOT NULL,
Nazwisko TEXT NOT NULL,
Wiek INTEGER NOT NULL,
Kurs TEXT NOT NULL
);
SELECT * FROM Pracownicy;
SELECT * FROM Pracownicy WHERE Wiek > 30;
SELECT * FROM Pracownicy WHERE Wiek < 30;
SELECT * FROM Pracownicy WHERE Nazwisko LIKE 'K%' AND Nazwisko LIKE '%KI';
ALTER TABLE Pracownicy 
RENAME COLUMN ID to NR;
SELECT * FROM Pracownicy WHERE NR IS NULL OR Imię IS NULL OR Nazwisko IS NULL OR Wiek IS NULL OR Kurs IS NULL;
SELECT * FROM Pracownicy WHERE Kurs = 'Java';
